<?php declare(strict_types = 1);

/*
 * This file is part of the Vairogs package.
 *
 * (c) Dāvis Zālītis (k0d3r1s) <davis@vairogs.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Vairogs\Assets\PhpCsFixerCustomFixers\Fixer\DataProvider;

class DoctrineMigrationsFixerDataProvider
{
    public static function provideFixCases(): iterable
    {
        yield 'remove doctrine autogenerated migration comments' => [
            <<<'EXPECTED'
                <?php

                declare(strict_types=1);

                namespace DoctrineMigrations;

                use Doctrine\DBAL\Schema\Schema;
                use Doctrine\Migrations\AbstractMigration;

                final class Version20250417114430 extends AbstractMigration
                {
                    public function getDescription(): string
                    {
                        return '';
                    }

                    public function up(Schema $schema): void
                    {
                        }

                    public function down(Schema $schema): void
                    {
                        }
                }
                EXPECTED
            ,
            <<<'INPUT'
                <?php

                declare(strict_types=1);

                namespace DoctrineMigrations;

                use Doctrine\DBAL\Schema\Schema;
                use Doctrine\Migrations\AbstractMigration;

                /**
                 * Auto-generated Migration: Please modify to your needs!
                 */
                final class Version20250417114430 extends AbstractMigration
                {
                    public function getDescription(): string
                    {
                        return '';
                    }

                    public function up(Schema $schema): void
                    {
                        // this up() migration is auto-generated, please modify it to your needs

                    }

                    public function down(Schema $schema): void
                    {
                        // this down() migration is auto-generated, please modify it to your needs

                    }
                }
                INPUT
        ];

        yield 'remove auto-generated comments but keep others' => [
            <<<'EXPECTED'
                <?php

                declare(strict_types=1);

                namespace DoctrineMigrations;

                use Doctrine\DBAL\Schema\Schema;
                use Doctrine\Migrations\AbstractMigration;

                final class Version20250417120000 extends AbstractMigration
                {
                    public function getDescription(): string
                    {
                        // returns the description
                        return '';
                    }

                    public function up(Schema $schema): void
                    {
                        // user-defined logic
                        $schema->createTable('test');
                    }

                    public function down(Schema $schema): void
                    {
                        // custom rollback logic
                        $schema->dropTable('test');
                    }
                }
                EXPECTED
            ,
            <<<'INPUT'
                <?php

                declare(strict_types=1);

                namespace DoctrineMigrations;

                use Doctrine\DBAL\Schema\Schema;
                use Doctrine\Migrations\AbstractMigration;

                /**
                 * Auto-generated Migration: Please modify to your needs!
                 */
                final class Version20250417120000 extends AbstractMigration
                {
                    public function getDescription(): string
                    {
                        // returns the description
                        return '';
                    }

                    public function up(Schema $schema): void
                    {
                        // this up() migration is auto-generated, please modify it to your needs
                        // user-defined logic
                        $schema->createTable('test');
                    }

                    public function down(Schema $schema): void
                    {
                        // this down() migration is auto-generated, please modify it to your needs
                        // custom rollback logic
                        $schema->dropTable('test');
                    }
                }
                INPUT
        ];

        yield 'filters docblock and replaces with T_COMMENT' => [
            <<<'EXPECTED'
                <?php

                declare(strict_types=1);

                namespace DoctrineMigrations;

                // This is an important migration
                final class Version20250417130000
                {
                }
                EXPECTED
            ,
            <<<'INPUT'
                <?php

                declare(strict_types=1);

                namespace DoctrineMigrations;

                /**
                 * Auto-generated Migration: Please modify to your needs!
                 * This is an important migration
                 */
                final class Version20250417130000
                {
                }
                INPUT
        ];
    }
}
