<?php declare(strict_types = 1);

/*
 * This file is part of the Vairogs package.
 *
 * (c) Dāvis Zālītis (k0d3r1s) <davis@vairogs.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Vairogs\Tests\PhpCsFixerCustomFixers;

use PhpCsFixer\Tokenizer\Tokens;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;
use SplFileInfo;
use Vairogs\PhpCsFixerCustomFixers\Fixer\DoctrineMigrationsFixer;

final class DoctrineMigrationsFixerTest extends TestCase
{
    #[DataProvider('provideFixCases')]
    public function testFix(
        string $expected,
        ?string $input = null,
    ): void {
        $fixer = new DoctrineMigrationsFixer();
        $file = new SplFileInfo('some/file.php');
        $tokens = Tokens::fromCode($input ?? $expected);

        $fixer->fix($file, $tokens);

        $tokens->clearEmptyTokens();
        $tokens->generateCode();

        $this->assertSame($expected, $tokens->generateCode());

        $tokens = Tokens::fromCode($tokens->generateCode());
        $fixer->fix($file, $tokens);
        $tokens->clearEmptyTokens();
        $this->assertSame($expected, $tokens->generateCode());
    }

    public static function provideFixCases(): iterable
    {
        yield 'remove doctrine autogenerated migration comments' => [
            <<<'EXPECTED'
                <?php

                declare(strict_types=1);

                namespace DoctrineMigrations;

                use Doctrine\DBAL\Schema\Schema;
                use Doctrine\Migrations\AbstractMigration;

                final class Version20250417114430 extends AbstractMigration
                {
                    public function getDescription(): string
                    {
                        return '';
                    }

                    public function up(Schema $schema): void
                    {
                        }

                    public function down(Schema $schema): void
                    {
                        }
                }
                EXPECTED
            ,
            <<<'INPUT'
                <?php

                declare(strict_types=1);

                namespace DoctrineMigrations;

                use Doctrine\DBAL\Schema\Schema;
                use Doctrine\Migrations\AbstractMigration;

                /**
                 * Auto-generated Migration: Please modify to your needs!
                 */
                final class Version20250417114430 extends AbstractMigration
                {
                    public function getDescription(): string
                    {
                        return '';
                    }

                    public function up(Schema $schema): void
                    {
                        // this up() migration is auto-generated, please modify it to your needs

                    }

                    public function down(Schema $schema): void
                    {
                        // this down() migration is auto-generated, please modify it to your needs

                    }
                }
                INPUT
        ];
    }
}
